default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: my_blog_rails_development

test:
  <<: *default
  database: my_blog_rails_test
  
production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :production, :db_name) %>
  username: <%= Rails.application.credentials.dig(:database, :production, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :production, :password) %>
  host: <%= Rails.application.credentials.dig(:database, :production, :host) %>
  port: <%= Rails.application.credentials.dig(:database, :production, :port) %>
